---
# WAITING: waiting on
# https://github.com/ansible-collections/community.general/issues/864 to be
# fixed so that re-running this task doesn't fail when the package is already
# installed.
- name: Install MacTeX
  homebrew:
    name: homebrew/cask/mactex-no-gui
    # name: "homebrew/cask/mactex-no-gui@{{ mactex_version }}"
    state: latest
