---
- name: Install coreutils
  homebrew:
    name: coreutils
    state: present

- homebrew:
    state: latest
    name:
      - binutils # don't link this so that there's no conflicts with
      # MacOS executables.
      - diffutils
      - gawk
      - gnutls
      - gzip
      - screen
      - watch
      - wget

- homebrew:
    state: latest
    name:
      - ed
      - findutils
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-which
      - grep

- name: Install wdiff
  homebrew:
    name: wdiff
    state: present
    install_options: with-gettext
