- name: Download Elgato Dock software 
  get_url:
    url: "https://edge.elgato.com/thunderbolt-dock/Elgato_Thunderbolt_Dock_Software_1.2.10.131_40.pkg"
    dest: "{{ downloads_directory }}/Elgato_Thunderbolt_Dock_Software_1.2.10.131_40.pkg"

- name: Install Elgato Dock software
  command: >
    installer -package "{{ downloads_directory }}/Elgato_Thunderbolt_Dock_Software_1.2.10.131_40.pkg" -target /
  become: yes
