---
- name: Download Python 3
  get_url:
    url: https://www.python.org/ftp/python/{{ python3_version }}/{{ python3_pkg }}
    dest: "{{ downloads_directory }}/{{ python3_pkg }}"

- name: Install Python 3
  command: >
    installer -package {{ downloads_directory }}/{{ python3_pkg }} -target /
  become: yes

- name: Install Python 3 SSL certificates
  command: >
    "/Applications/Python {{ python3_version_major_minor }}/Install Certificates.command"
  become_user: mpereira # FIXME: hard-coded user name.
