---
ffmpeg_directory: Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_{{ ffmpeg_version }}
ffmpeg_zip: "{{ ffmpeg_directory }}.zip"
ffmpeg_url: https://evermeet.cx/ffmpeg/ffmpeg-4.2.2.7z{{ ffmpeg_zip }}
ffmpeg_checksum: md5:92e3c5a890c6e306d4a5940cee06de27
