---
# WAITING: waiting on
# https://github.com/ansible-collections/community.general/issues/864 to be
# fixed so that re-running this task doesn't fail when the package is already
# installed.
- name: Install OpenZFS
  homebrew:
    name: homebrew/cask/openzfs
    # name: "homebrew/cask/openzfs@{{ openzfs_version }}"
    state: latest
