---
- name: Add Homebrew tap
  command: >
    brew tap daviderestivo/emacs-head

- name: Install Emacs
  homebrew:
    name: emacs-head@28
    state: latest
    install_options: with-cocoa,with-crash-debug,with-dbus,with-xwidgets,with-modern-icon-pen,with-pdumper
