---
- lineinfile:
    path: "/etc/sudoers.d/mpereira" # FIXME: hard-coded user name.
    line: "mpereira ALL=(ALL) NOPASSWD: ALL" # FIXME: hard-coded user name.
    create: yes
    owner: root
    mode: 0644
    validate: 'visudo -cf %s'
  become: yes
