---
- name: Download Neovim
  get_url:
    url="https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim-macos.tar.gz"
    dest="{{ downloads_directory }}/nvim-macos.tar.gz"

- name: Extract Neovim
  command: >
    tar -xvf {{ downloads_directory }}/nvim-macos.tar.gz
        -C {{ downloads_directory }}
    creates={{ downloads_directory }}/nvim-osx64

- name: Install nvim binary
  command: >
    cp -R {{ downloads_directory }}/nvim-osx64 /opt/nvim-{{ neovim_version }}
  become: yes
